# Generated by Django 4.2.10 on 2024-02-29 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataAnalysisProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("Python", "Python"),
                            ("SQL", "SQL"),
                            ("Tableau", "Tableau"),
                            ("Power BI", "Power BI"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(max_length=250)),
                ("published_date", models.DateField(default=django.utils.timezone.now)),
                ("problem_statement", models.TextField()),
                ("insights", models.TextField()),
                (
                    "html_file",
                    models.FileField(blank=True, null=True, upload_to="html_files/"),
                ),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="pdf_files/"),
                ),
                (
                    "analyst",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Project",
        ),
    ]
