# Generated by Django 4.2.10 on 2024-02-29 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects_app", "0002_dataanalysisproject_delete_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataanalysisproject",
            name="analyst",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dataanalysisproject",
            name="description",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="dataanalysisproject",
            name="insights",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dataanalysisproject",
            name="problem_statement",
            field=models.TextField(blank=True, null=True),
        ),
    ]
