# Generated by Django 4.2.10 on 2024-02-29 23:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects_app", "0003_alter_dataanalysisproject_analyst_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dataanalysisproject",
            options={"verbose_name_plural": "Data Analysis Projects"},
        ),
        migrations.AddField(
            model_name="dataanalysisproject",
            name="data_source",
            field=models.URLField(
                blank=True, default="Local", max_length=250, null=True
            ),
        ),
    ]
