# Generated by Django 4.2.10 on 2024-02-29 23:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects_app", "0004_alter_dataanalysisproject_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataanalysisproject",
            name="data_source",
            field=models.URLField(
                blank=True, default="local.io", max_length=250, null=True
            ),
        ),
    ]
