# Generated by Django 4.2.10 on 2024-02-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects_app", "0005_alter_dataanalysisproject_data_source"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dataanalysisproject",
            old_name="analysis_type",
            new_name="tools",
        ),
        migrations.AddField(
            model_name="dataanalysisproject",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("Data Analysis", "Data Analysis"),
                    ("Data Engineering", "Data Engineering"),
                    ("Machine Learning", "Machine Learning"),
                ],
                default="Data Analysis",
                max_length=35,
            ),
        ),
    ]
