# Generated by Django 4.2.10 on 2024-02-29 23:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "projects_app",
            "0006_rename_analysis_type_dataanalysisproject_tools_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name="dataanalysisproject",
            name="tools",
        ),
        migrations.AddField(
            model_name="dataanalysisproject",
            name="tools",
            field=models.ManyToManyField(
                choices=[
                    ("Python", "Python"),
                    ("SQL", "SQL"),
                    ("Tableau", "Tableau"),
                    ("Power BI", "Power BI"),
                ],
                to="projects_app.tool",
            ),
        ),
    ]
