# Generated by Django 4.2.10 on 2024-03-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects_app", "0007_tool_remove_dataanalysisproject_tools_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tool",
            name="name",
            field=models.CharField(max_length=25),
        ),
    ]
