# Generated by Django 4.2.10 on 2024-03-01 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects_app", "0008_alter_tool_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataanalysisproject",
            name="tools",
            field=models.ManyToManyField(to="projects_app.tool"),
        ),
    ]
