# Generated by Django 4.2.10 on 2024-03-01 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects_app", "0009_alter_dataanalysisproject_tools"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tool",
            name="name",
            field=models.CharField(
                choices=[
                    ("Python", "Python"),
                    ("SQL", "SQL"),
                    ("Tableau", "Tableau"),
                    ("Power BI", "Power BI"),
                ],
                max_length=25,
            ),
        ),
    ]
