# Generated by Django 4.2.10 on 2024-03-03 02:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects_app", "0012_alter_dataanalysisproject_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataanalysisproject",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="project_pics/"),
        ),
    ]
