# Generated by Django 4.2.10 on 2024-03-03 02:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects_app", "0013_dataanalysisproject_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dataanalysisproject",
            old_name="image",
            new_name="project_photo",
        ),
    ]
