# Generated by Django 4.2.10 on 2024-05-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects_app", "0014_rename_image_dataanalysisproject_project_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataanalysisproject",
            name="html_file",
            field=models.FileField(
                blank=True, default="default.html", null=True, upload_to="html_files/"
            ),
        ),
    ]
