# Generated by Django 4.2.10 on 2024-06-08 00:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects_app", "0017_alter_dataanalysisproject_html_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataanalysisproject",
            name="app_image",
            field=models.ImageField(blank=True, null=True, upload_to="app_pics/"),
        ),
    ]
