# Generated by Django 4.2.10 on 2024-06-08 00:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects_app", "0018_dataanalysisproject_app_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataanalysisproject",
            name="app_image",
            field=models.ImageField(blank=True, null=True, upload_to="project_pics/"),
        ),
    ]
