# Generated by Django 4.2.10 on 2024-06-08 00:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects_app", "0019_alter_dataanalysisproject_app_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dataanalysisproject",
            name="app_image",
        ),
    ]
