# Generated by Django 4.2.10 on 2024-07-29 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects_app", "0021_alter_dataanalysisproject_project_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataanalysisproject",
            name="html_file",
            field=models.FileField(
                blank=True,
                default="default.html",
                max_length=250,
                null=True,
                upload_to="html_files/",
            ),
        ),
        migrations.AlterField(
            model_name="dataanalysisproject",
            name="pdf_file",
            field=models.FileField(
                blank=True, max_length=250, null=True, upload_to="pdf_files/"
            ),
        ),
        migrations.AlterField(
            model_name="dataanalysisproject",
            name="project_photo",
            field=models.ImageField(
                blank=True, max_length=250, null=True, upload_to="project_pics/"
            ),
        ),
    ]
