# Generated by Django 4.2.10 on 2025-03-30 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects_app', '0023_alter_dataanalysisproject_data_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(blank=True, choices=[('Data Analysis', 'Data Analysis'), ('Data Engineering', 'Data Engineering'), ('Cybersecurity', 'Cybersecurity'), ('Machine Learning', 'Machine Learning'), ('Artificial Intelligence', 'AI Projects')], max_length=100, null=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
                ('problem_statement', models.TextField(blank=True, null=True)),
                ('insights', models.TextField(blank=True, null=True)),
                ('html_file', models.FileField(blank=True, default='default.html', max_length=250, null=True, upload_to='html_files/')),
                ('pdf_file', models.FileField(blank=True, max_length=250, null=True, upload_to='pdf_files/')),
                ('project_photo', models.ImageField(blank=True, max_length=250, null=True, upload_to='project_pics/')),
                ('data_source', models.URLField(blank=True, default='https://www.thedatamatrix.ca/', max_length=250, null=True)),
                ('analyst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tools', models.ManyToManyField(to='projects_app.tool')),
            ],
            options={
                'verbose_name_plural': 'My Projects',
            },
        ),
        migrations.DeleteModel(
            name='DataAnalysisProject',
        ),
    ]
