# Generated by Django 4.2.10 on 2025-03-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0024_myprojects_delete_dataanalysisproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(blank=True, max_length=35, null=True)),
            ],
        ),
    ]
