# Generated by Django 4.2.10 on 2025-03-30 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0025_projectlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprojects',
            name='project_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects_app.projectlist'),
        ),
    ]
