# Generated by Django 4.2.10 on 2025-03-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0026_alter_myprojects_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprojects',
            name='project_type',
            field=models.CharField(blank=True, choices=[('Data Analysis', 'Data Analysis'), ('Data Engineering', 'Data Engineering'), ('Cybersecurity', 'Cybersecurity'), ('Machine Learning', 'Machine Learning'), ('Artificial Intelligence', 'AI Projects')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ProjectList',
        ),
    ]
