# Generated by Django 4.2.10 on 2025-03-30 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0027_alter_myprojects_project_type_delete_projectlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(blank=True, max_length=35, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='myprojects',
            name='project_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects_app.projectlist'),
        ),
    ]
