# Generated by Django 4.2.10 on 2025-04-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0028_projectlist_alter_myprojects_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprojects',
            name='project_photo',
            field=models.ImageField(blank=True, default='default.jpeg', max_length=250, null=True, upload_to='project_pics/'),
        ),
        migrations.AlterField(
            model_name='projectlist',
            name='project_type',
            field=models.CharField(blank=True, max_length=35, null=True, unique=True),
        ),
    ]
