# Generated by Django 4.2.20 on 2025-08-28 01:50

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0030_alter_myprojects_html_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprojects',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='myprojects',
            name='flowchart_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
