# Generated by Django 4.2.20 on 2025-08-28 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0031_myprojects_content_myprojects_flowchart_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprojects',
            name='flowchart_data',
        ),
    ]
