# Generated by Django 4.2.20 on 2025-08-28 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0033_node_edge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Edge',
        ),
        migrations.DeleteModel(
            name='Node',
        ),
    ]
