# Generated by Django 4.2.10 on 2024-03-01 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="test",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
