# Generated by Django 4.2.10 on 2024-03-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_profile", "0002_profile_test"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsTools",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="CloudStack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="Databases",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="DataStack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="Languages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="Positions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name="profile",
            name="test",
        ),
        migrations.AddField(
            model_name="profile",
            name="career_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="analytics_tools",
            field=models.ManyToManyField(to="my_profile.analyticstools"),
        ),
        migrations.AddField(
            model_name="profile",
            name="cloud_stack",
            field=models.ManyToManyField(to="my_profile.cloudstack"),
        ),
        migrations.AddField(
            model_name="profile",
            name="data_stack",
            field=models.ManyToManyField(to="my_profile.datastack"),
        ),
        migrations.AddField(
            model_name="profile",
            name="databases",
            field=models.ManyToManyField(to="my_profile.databases"),
        ),
        migrations.AddField(
            model_name="profile",
            name="languages",
            field=models.ManyToManyField(to="my_profile.languages"),
        ),
        migrations.AddField(
            model_name="profile",
            name="positions",
            field=models.ManyToManyField(to="my_profile.positions"),
        ),
    ]
