# Generated by Django 4.2.10 on 2024-03-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_profile", "0003_analyticstools_cloudstack_databases_datastack_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebFramework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
            ],
        ),
    ]
