# Generated by Django 4.2.10 on 2024-03-01 23:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("my_profile", "0005_profile_web_frameworks"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="analyticstools",
            options={"verbose_name_plural": "Analytics Tools"},
        ),
        migrations.AlterModelOptions(
            name="cloudstack",
            options={"verbose_name_plural": "Cloud Stack"},
        ),
        migrations.AlterModelOptions(
            name="databases",
            options={"verbose_name_plural": "Databases"},
        ),
        migrations.AlterModelOptions(
            name="datastack",
            options={"verbose_name_plural": "Data Stack"},
        ),
        migrations.AlterModelOptions(
            name="languages",
            options={"verbose_name_plural": "Languages"},
        ),
        migrations.AlterModelOptions(
            name="positions",
            options={"verbose_name_plural": "Position"},
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name_plural": "Profiles"},
        ),
        migrations.AlterModelOptions(
            name="webframework",
            options={"verbose_name_plural": "Web Frameworks"},
        ),
    ]
