# Generated by Django 4.2.10 on 2024-03-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_profile", "0006_alter_analyticstools_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="website",
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
