# Generated by Django 4.2.10 on 2024-03-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_profile", "0007_profile_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="Country",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="city",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
