# Generated by Django 4.2.10 on 2024-03-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_profile", "0008_profile_country_profile_city"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "designation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("company", models.CharField(blank=True, max_length=100, null=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("responsibilities", models.TextField(blank=True, null=True)),
                ("achievement", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="Country",
            new_name="country",
        ),
    ]
