# Generated by Django 4.2.10 on 2024-03-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_profile", "0009_experience_rename_country_profile_country"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="experience",
            options={"verbose_name_plural": "Experience"},
        ),
        migrations.AddField(
            model_name="experience",
            name="industry",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
