# Generated by Django 4.2.10 on 2024-05-21 02:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("my_profile", "0010_alter_experience_options_experience_industry"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="languages",
            new_name="programming_languages",
        ),
    ]
