# Generated by Django 4.2.10 on 2024-05-27 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_profile", "0012_alter_experience_end_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competencies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                "verbose_name_plural": "Competencies",
            },
        ),
    ]
