# Generated by Django 4.2.10 on 2024-05-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_profile", "0013_competencies"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="competencies",
            field=models.ManyToManyField(to="my_profile.competencies"),
        ),
    ]
