# Generated by Django 4.2.10 on 2024-06-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_profile", "0014_profile_competencies"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("url", models.URLField()),
            ],
            options={
                "verbose_name_plural": "Profile Links",
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="links",
            field=models.ManyToManyField(blank=True, to="my_profile.profilelink"),
        ),
    ]
