# Generated by Django 4.2.10 on 2024-06-08 00:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("my_profile", "0015_profilelink_profile_links"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="links",
        ),
        migrations.DeleteModel(
            name="ProfileLink",
        ),
    ]
