# Generated by Django 4.2.10 on 2024-07-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_profile", "0017_profilelink"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "Interests",
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="interests",
            field=models.ManyToManyField(to="my_profile.interests"),
        ),
    ]
