# Generated by Django 4.2.10 on 2024-07-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_profile", "0018_interests_profile_interests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interests",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
