# Generated by Django 4.2.20 on 2025-08-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0019_alter_interests_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralCybersecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'General Cybersecurity',
            },
        ),
        migrations.CreateModel(
            name='IAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'IAM',
            },
        ),
        migrations.CreateModel(
            name='NetworkAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Network & Traffic Analysis',
            },
        ),
        migrations.CreateModel(
            name='SecurityFrameworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Security Frameworks',
            },
        ),
        migrations.CreateModel(
            name='SIEM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'SIEM',
            },
        ),
        migrations.CreateModel(
            name='VulnerabilityManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Vulnerability Management',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='general_cybersecurity',
            field=models.ManyToManyField(related_name='general_cybersecurity', to='my_profile.generalcybersecurity'),
        ),
        migrations.AddField(
            model_name='profile',
            name='iam_skills',
            field=models.ManyToManyField(related_name='iam_skills', to='my_profile.iam'),
        ),
        migrations.AddField(
            model_name='profile',
            name='network_analysis',
            field=models.ManyToManyField(related_name='network_analysis', to='my_profile.networkanalysis'),
        ),
        migrations.AddField(
            model_name='profile',
            name='security_frameworks',
            field=models.ManyToManyField(related_name='security_frameworks', to='my_profile.securityframeworks'),
        ),
        migrations.AddField(
            model_name='profile',
            name='siem_tools',
            field=models.ManyToManyField(related_name='siem_tools', to='my_profile.siem'),
        ),
        migrations.AddField(
            model_name='profile',
            name='vulnerability_management',
            field=models.ManyToManyField(related_name='vulnerability_management', to='my_profile.vulnerabilitymanagement'),
        ),
    ]
