# Generated by Django 4.2.20 on 2025-08-19 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0020_generalcybersecurity_iam_networkanalysis_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iam',
            options={'verbose_name_plural': 'IAM Skills'},
        ),
        migrations.AlterModelOptions(
            name='networkanalysis',
            options={'verbose_name_plural': 'Network Analysis'},
        ),
        migrations.AlterModelOptions(
            name='positions',
            options={'verbose_name_plural': 'Positions'},
        ),
        migrations.AlterModelOptions(
            name='siem',
            options={'verbose_name_plural': 'SIEM Tools'},
        ),
        migrations.AddField(
            model_name='profilelink',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile_links', to='my_profile.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analyticstools',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cloudstack',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='competencies',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='databases',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datastack',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='languages',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='positions',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='analytics_tools',
            field=models.ManyToManyField(blank=True, to='my_profile.analyticstools'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cloud_stack',
            field=models.ManyToManyField(blank=True, to='my_profile.cloudstack'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='competencies',
            field=models.ManyToManyField(blank=True, to='my_profile.competencies'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='data_stack',
            field=models.ManyToManyField(blank=True, to='my_profile.datastack'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='databases',
            field=models.ManyToManyField(blank=True, to='my_profile.databases'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='general_cybersecurity',
            field=models.ManyToManyField(blank=True, to='my_profile.generalcybersecurity'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='iam_skills',
            field=models.ManyToManyField(blank=True, to='my_profile.iam'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(blank=True, to='my_profile.interests'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='network_analysis',
            field=models.ManyToManyField(blank=True, to='my_profile.networkanalysis'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='positions',
            field=models.ManyToManyField(blank=True, to='my_profile.positions'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='programming_languages',
            field=models.ManyToManyField(blank=True, to='my_profile.languages'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='security_frameworks',
            field=models.ManyToManyField(blank=True, to='my_profile.securityframeworks'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='siem_tools',
            field=models.ManyToManyField(blank=True, to='my_profile.siem'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vulnerability_management',
            field=models.ManyToManyField(blank=True, to='my_profile.vulnerabilitymanagement'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='web_frameworks',
            field=models.ManyToManyField(blank=True, to='my_profile.webframework'),
        ),
        migrations.AlterField(
            model_name='webframework',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
