# Generated by Django 4.2.20 on 2025-08-28 03:31

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0021_alter_iam_options_alter_networkanalysis_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='achievement',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='responsibilities',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='career_summary',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Text'),
        ),
    ]
